#!/bin/bash
python3  ./code/rsidmap_v2.py --build hg19 --chr_col chr.iCOGs --pos_col Position.iCOGs --ref_col Baseline.Meta --alt_col Effect.Meta --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/BRCA_transfer.gz  --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/BRCA_transfer_remap
python3  ./code/rsidmap_v2.py --build hg19 --chr_col chromosome --pos_col base_pair_location --ref_col other_allele --alt_col effect_allele --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/lung_transfer.gz  --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/lung_transfer_remap
python3  ./code/rsidmap_v2.py --build hg19 --chr_col chromosome --pos_col base_pair_location --ref_col other_allele --alt_col effect_allele --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/PRAD_transfer.gz  --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/PRAD_transfer_remap
python3  ./code/rsidmap_v2.py --build hg19 --chr_col chromosome --pos_col base_pair_location --ref_col other_allele --alt_col effect_allele --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/UCEC_transfer.gz  --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/UCEC_transfer_remap
python3  ./code/rsidmap_v2.py --build hg19 --chr_col Chromosome --pos_col Position --ref_col Baseline --alt_col Effect --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/OV_transfer.gz  --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/OV_transfer_remap
python3  ./code/rsidmap_v2.py --build hg19 --chr_col chromosome --pos_col base_pair_location --ref_col other_allele --alt_col effect_allele --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/CRC_transfer.gz  --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/CRC_transfer_remap
python3  ./code/rsidmap_v2.py --build hg19 --chr_col chromosome --pos_col base_pair_location --ref_col other_allele --alt_col effect_allele --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/ESCA_transfer.gz  --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/ESCA_transfer_remap
python3  ./code/rsidmap_v2.py --build hg19 --chr_col chromosome --pos_col base_pair_location --ref_col other_allele --alt_col effect_allele --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/CESC-HL-LL_transfer.gz --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/CESC-HL-LL_transfer_remap

# finngen
python3  ./code/rsidmap_v2.py --build hg38 --chr_col "#chrom" --pos_col pos --ref_col  ref --alt_col alt --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/BLCA_transfer.gz  --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/BLCA_transfer_remap
python3  ./code/rsidmap_v2.py --build hg38 --chr_col "#chrom" --pos_col pos --ref_col  ref --alt_col alt --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/HNSC_transfer.gz  --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/HNSC_transfer_remap
python3  ./code/rsidmap_v2.py --build hg38 --chr_col "#chrom" --pos_col pos --ref_col  ref --alt_col alt --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/kidney_transfer.gz  --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/kidney_transfer_remap
python3  ./code/rsidmap_v2.py --build hg38 --chr_col "#chrom" --pos_col pos --ref_col  ref --alt_col alt --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/SKCM_transfer.gz  --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/SKCM_transfer_remap
python3  ./code/rsidmap_v2.py --build hg38 --chr_col "#chrom" --pos_col pos --ref_col  ref --alt_col alt --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/PAAD_transfer.gz  --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/PAAD_transfer_remap
python3  ./code/rsidmap_v2.py --build hg38 --chr_col "#chrom" --pos_col pos --ref_col  ref --alt_col alt --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/DLBC_transfer.gz  --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/DLBC_transfer_remap
python3  ./code/rsidmap_v2.py --build hg38 --chr_col "#chrom" --pos_col pos --ref_col  ref --alt_col alt --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/BGC_transfer.gz  --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/BGC_transfer_remap
python3  ./code/rsidmap_v2.py --build hg38 --chr_col "#chrom" --pos_col pos --ref_col  ref --alt_col alt --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/STAD_transfer.gz  --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/STAD_transfer_remap
python3  ./code/rsidmap_v2.py --build hg38 --chr_col "#chrom" --pos_col pos --ref_col  ref --alt_col alt --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/THCA_transfer.gz  --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/THCA_transfer_remap
python3  ./code/rsidmap_v2.py --build hg38 --chr_col "#chrom" --pos_col pos --ref_col  ref --alt_col alt --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/finngen_transfer.gz --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/finngen_transfer_remap
python3  ./code/rsidmap_v2.py --build hg38 --chr_col "#chrom" --pos_col pos --ref_col  ref --alt_col alt --file_gwas /home/yanyq/share_genetics/data/GWAS/rsidmap/finngen_BCC_SCC_rest_transfer.gz --file_out /home/yanyq/share_genetics/data/GWAS/rsidmap/finngen_BCC_SCC_rest_transfer_remap
