nohup ./LAVA_run_BLCA-BRCA.sh >& log/LAVA_run_BLCA-BRCA.log &
nohup ./LAVA_run_BLCA-HNSC.sh >& log/LAVA_run_BLCA-HNSC.log &
nohup ./LAVA_run_BLCA-kidney.sh >& log/LAVA_run_BLCA-kidney.log &
nohup ./LAVA_run_BLCA-lung.sh >& log/LAVA_run_BLCA-lung.log &
nohup ./LAVA_run_BLCA-OV.sh >& log/LAVA_run_BLCA-OV.log &
nohup ./LAVA_run_BLCA-PAAD.sh >& log/LAVA_run_BLCA-PAAD.log &
nohup ./LAVA_run_BLCA-PRAD.sh >& log/LAVA_run_BLCA-PRAD.log &
nohup ./LAVA_run_BLCA-SKCM.sh >& log/LAVA_run_BLCA-SKCM.log &
nohup ./LAVA_run_BLCA-UCEC.sh >& log/LAVA_run_BLCA-UCEC.log &
nohup ./LAVA_run_BRCA-HNSC.sh >& log/LAVA_run_BRCA-HNSC.log &
nohup ./LAVA_run_BRCA-kidney.sh >& log/LAVA_run_BRCA-kidney.log &
nohup ./LAVA_run_BRCA-lung.sh >& log/LAVA_run_BRCA-lung.log &
nohup ./LAVA_run_BRCA-OV.sh >& log/LAVA_run_BRCA-OV.log &
nohup ./LAVA_run_BRCA-PAAD.sh >& log/LAVA_run_BRCA-PAAD.log &
nohup ./LAVA_run_BRCA-PRAD.sh >& log/LAVA_run_BRCA-PRAD.log &
nohup ./LAVA_run_BRCA-SKCM.sh >& log/LAVA_run_BRCA-SKCM.log &
nohup ./LAVA_run_BRCA-UCEC.sh >& log/LAVA_run_BRCA-UCEC.log &
nohup ./LAVA_run_HNSC-kidney.sh >& log/LAVA_run_HNSC-kidney.log &
nohup ./LAVA_run_HNSC-lung.sh >& log/LAVA_run_HNSC-lung.log &
nohup ./LAVA_run_HNSC-OV.sh >& log/LAVA_run_HNSC-OV.log &
nohup ./LAVA_run_HNSC-PAAD.sh >& log/LAVA_run_HNSC-PAAD.log &
nohup ./LAVA_run_HNSC-PRAD.sh >& log/LAVA_run_HNSC-PRAD.log &
nohup ./LAVA_run_HNSC-SKCM.sh >& log/LAVA_run_HNSC-SKCM.log &
nohup ./LAVA_run_HNSC-UCEC.sh >& log/LAVA_run_HNSC-UCEC.log &
nohup ./LAVA_run_kidney-lung.sh >& log/LAVA_run_kidney-lung.log &
nohup ./LAVA_run_kidney-OV.sh >& log/LAVA_run_kidney-OV.log &
nohup ./LAVA_run_kidney-PAAD.sh >& log/LAVA_run_kidney-PAAD.log &
nohup ./LAVA_run_kidney-PRAD.sh >& log/LAVA_run_kidney-PRAD.log &
nohup ./LAVA_run_kidney-SKCM.sh >& log/LAVA_run_kidney-SKCM.log &
nohup ./LAVA_run_kidney-UCEC.sh >& log/LAVA_run_kidney-UCEC.log &
nohup ./LAVA_run_lung-OV.sh >& log/LAVA_run_lung-OV.log &
nohup ./LAVA_run_lung-PAAD.sh >& log/LAVA_run_lung-PAAD.log &
nohup ./LAVA_run_lung-PRAD.sh >& log/LAVA_run_lung-PRAD.log &
nohup ./LAVA_run_lung-SKCM.sh >& log/LAVA_run_lung-SKCM.log &
nohup ./LAVA_run_lung-UCEC.sh >& log/LAVA_run_lung-UCEC.log &
nohup ./LAVA_run_OV-PAAD.sh >& log/LAVA_run_OV-PAAD.log &
nohup ./LAVA_run_OV-PRAD.sh >& log/LAVA_run_OV-PRAD.log &
nohup ./LAVA_run_OV-SKCM.sh >& log/LAVA_run_OV-SKCM.log &
nohup ./LAVA_run_OV-UCEC.sh >& log/LAVA_run_OV-UCEC.log &
nohup ./LAVA_run_PAAD-PRAD.sh >& log/LAVA_run_PAAD-PRAD.log &
nohup ./LAVA_run_PAAD-SKCM.sh >& log/LAVA_run_PAAD-SKCM.log &
nohup ./LAVA_run_PAAD-UCEC.sh >& log/LAVA_run_PAAD-UCEC.log &
nohup ./LAVA_run_PRAD-SKCM.sh >& log/LAVA_run_PRAD-SKCM.log &
nohup ./LAVA_run_PRAD-UCEC.sh >& log/LAVA_run_PRAD-UCEC.log &
nohup ./LAVA_run_SKCM-UCEC.sh >& log/LAVA_run_SKCM-UCEC.log &
