V1	V2
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BLCA-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BLCA-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BLCA-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BLCA-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BLCA-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BLCA-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BLCA-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BLCA-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BLCA-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BRCA-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BRCA-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BRCA-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BRCA-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BRCA-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BRCA-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BRCA-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BRCA-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HNSC-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HNSC-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HNSC-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HNSC-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HNSC-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HNSC-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HNSC-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/kidney-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/kidney-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/kidney-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/kidney-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/kidney-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/kidney-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/lung-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/lung-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/lung-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/lung-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/lung-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/OV-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/OV-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/OV-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/OV-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/PAAD-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/PAAD-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/PAAD-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/PRAD-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/PRAD-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SKCM-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGC-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGC-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGC-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGC-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGC-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CRC-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CRC-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CRC-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CRC-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/DLBC-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/DLBC-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/DLBC-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/ESCA-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/ESCA-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/STAD-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-BAC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-BCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-BGA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-BM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-CESC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-CML.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-CORP.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-EYAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-GSS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-HL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-LIHC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-LL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-MCL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-MESO.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-MM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-MS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-MZBL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-BCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-BGA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-BM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-CESC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-CML.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-CORP.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-EYAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-GSS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-HL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-LIHC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-LL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-MCL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-MESO.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-MM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-MS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-MZBL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-BGA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-BM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-CESC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-CML.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-CORP.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-EYAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-GSS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-HL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-LIHC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-LL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-MCL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-MESO.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-MM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-MS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-MZBL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-BM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-CESC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-CML.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-CORP.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-EYAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-GSS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-HL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-LIHC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-LL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-MCL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-MESO.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-MM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-MS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-MZBL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-CESC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-CML.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-CORP.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-EYAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-GSS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-HL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-LIHC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-LL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-MCL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-MESO.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-MM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-MS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-MZBL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-CML.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-CORP.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-EYAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-GSS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-HL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-LIHC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-LL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-MCL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-MESO.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-MM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-MS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-MZBL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-CORP.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-EYAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-GSS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-HL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-LIHC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-LL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-MCL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-MESO.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-MM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-MS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-MZBL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-EYAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-GSS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-HL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-LIHC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-LL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-MCL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-MESO.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-MM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-MS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-MZBL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-GSS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-HL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-LIHC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-LL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-MCL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-MESO.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-MM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-MS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-MZBL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-HL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-LIHC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-LL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-MCL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-MESO.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-MM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-MS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-MZBL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-LIHC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-LL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-MCL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-MESO.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-MM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-MS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-MZBL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-LL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-MCL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-MESO.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-MM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-MS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-MZBL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-MCL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-MESO.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-MM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-MS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-MZBL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-MESO.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-MM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-MS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-MZBL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-MM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-MS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-MZBL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-MS.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-MZBL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-MZBL.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-SCC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-SI.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-TEST.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-VULVA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGC-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGC-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGC-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGC-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGC-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGC-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGC-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGC-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGC-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGC-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CRC-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CRC-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CRC-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CRC-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CRC-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CRC-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CRC-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CRC-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CRC-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CRC-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/DLBC-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/DLBC-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/DLBC-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/DLBC-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/DLBC-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/DLBC-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/DLBC-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/DLBC-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/DLBC-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/DLBC-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/ESCA-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/ESCA-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/ESCA-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/ESCA-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/ESCA-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/ESCA-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/ESCA-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/ESCA-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/ESCA-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/ESCA-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/STAD-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/STAD-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/STAD-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/STAD-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/STAD-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/STAD-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/STAD-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/STAD-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/STAD-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/STAD-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/THCA-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/THCA-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/THCA-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/THCA-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/THCA-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/THCA-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/THCA-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/THCA-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/THCA-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/THCA-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CESC-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CML-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/CORP-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/EYAD-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/GSS-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/HL-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LIHC-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/LL-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MCL-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MESO-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MM-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MS-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/MZBL-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SCC-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-THCA.sh
