bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/SI-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/TEST-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-BLCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-BRCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-HNSC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-kidney.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-lung.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-OV.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-PAAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-PRAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-SKCM.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/VULVA-UCEC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/AML-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BAC-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BCC-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-ESCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-STAD.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BGA-THCA.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-BGC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-CRC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-DLBC.sh
bash	/home/yanyq/share_genetics/pipeline/code/1.6.3.SUPERGNOVA_run/BM-ESCA.sh
